In [248]:
import pandas as pd 
import numpy as np
import os
import matplotlib.pyplot as plt
import cv2
from sklearn import preprocessing

In [249]:
path_train = r"F:\python\EveryDayCoding\ComputerVision\HumanEmotion\Dataset\train"
path_test = r"F:\python\EveryDayCoding\ComputerVision\HumanEmotion\Dataset\test"

In [250]:
def get_data(path:str) -> "X, y":
    X = []
    y = []
    for i in os.listdir(path):
        for j in os.listdir(path + "/" + i):
            image_read = cv2.imread(f"{path}/{i}/{j}", cv2.IMREAD_GRAYSCALE)
            image_read = image_read.reshape(image_read.shape[0] * image_read.shape[1])/255
            X.append(image_read)
            y.append(i)
            
    return X, y


In [251]:
df_train_X, df_train_y = get_data(path_train)
df_test_X, df_test_y = get_data(path_test)

(28709, 2304)

(28709,)

In [255]:
encode_type = preprocessing.LabelEncoder()

In [256]:
df_train_y = encode_type.fit_transform(df_train_y)
df_test_y = encode_type.fit_transform(df_test_y)

In [257]:
np.unique(df_train_y)

array([0, 1, 2, 3, 4, 5, 6], dtype=int64)

In [258]:
print("encode y test data\n")
for numerik, nominal in zip(np.unique(df_test_y), encode_type.inverse_transform(np.unique(df_test_y))):
    print(f"{numerik} --> {nominal}")

encode y test data

0 --> angry
1 --> disgust
2 --> fear
3 --> happy
4 --> neutral
5 --> sad
6 --> surprise


In [259]:
print("encode y train data\n")
for numerik, nominal in zip(np.unique(df_train_y), encode_type.inverse_transform(np.unique(df_train_y))):
    print(f"{numerik} --> {nominal}")

encode y train data

0 --> angry
1 --> disgust
2 --> fear
3 --> happy
4 --> neutral
5 --> sad
6 --> surprise


In [269]:
np.shape(df_train_X)


(28709, 2304)

In [270]:
np.shape(df_train_y)

(28709,)

In [277]:
tf.stack(df_train_X)

<tf.Tensor: shape=(28709, 2304), dtype=float64, numpy=
array([[0.19607843, 0.1254902 , 0.05882353, ..., 0.56078431, 0.53333333,
        0.3254902 ],
       [0.11372549, 0.09411765, 0.11372549, ..., 0.05882353, 0.09411765,
        0.09411765],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.48627451, 0.50588235, 0.49019608, ..., 0.98039216, 0.95294118,
        0.98431373],
       [0.94901961, 0.94901961, 0.94901961, ..., 0.66666667, 0.76470588,
        0.79607843],
       [0.76078431, 0.77254902, 0.74901961, ..., 1.        , 1.        ,
        1.        ]])>

In [271]:
import tensorflow as tf
from tensorflow import keras
%matplotlib inline

In [280]:
model = keras.Sequential(
[
    keras.layers.Dense(200, input_shape = (np.shape(df_train_X)[1],), activation = "sigmoid" ),
    keras.layers.Dense(100, activation = "sigmoid"),
    keras.layers.Dense(7, activation = "sigmoid")
])

In [281]:
model.compile(optimizer='adam',
             loss = 'sparse_categorical_crossentropy',
             metrics = ['accuracy'])

In [282]:
model.fit(tf.stack(df_train_X), df_train_y, epochs=20)

Epoch 1/20
898/898 [==============================] - 12s 6ms/step - loss: 1.7869 - accuracy: 0.2627
Epoch 2/20
898/898 [==============================] - 6s 7ms/step - loss: 1.7215 - accuracy: 0.3156
Epoch 3/20
898/898 [==============================] - 6s 6ms/step - loss: 1.6997 - accuracy: 0.3300
Epoch 4/20
898/898 [==============================] - 5s 6ms/step - loss: 1.6822 - accuracy: 0.3390
Epoch 5/20
898/898 [==============================] - 5s 6ms/step - loss: 1.6643 - accuracy: 0.3475
Epoch 6/20
898/898 [==============================] - 5s 6ms/step - loss: 1.6536 - accuracy: 0.3519
Epoch 7/20
898/898 [==============================] - 5s 6ms/step - loss: 1.6452 - accuracy: 0.3586
Epoch 8/20
898/898 [==============================] - 5s 6ms/step - loss: 1.6352 - accuracy: 0.3621
Epoch 9/20
898/898 [==============================] - 5s 6ms/step - loss: 1.6304 - accuracy: 0.3609
Epoch 10/20
898/898 [==============================] - 5s 6ms/step - loss: 1.6173 - accuracy: 0.366

In [283]:
model.evaluate(tf.stack(df_test_X), df_test_y)

225/225 [==============================] - 4s 2ms/step - loss: 1.6616 - accuracy: 0.3376


[1.6616324186325073, 0.33755922317504883]

In [ ]:
confusion_matrix = tf.math.confusion_matrix(labels=Y_test, predictions=Y_predict_label)
plt.pyplot.figure(figsize = (10,7))
sn.heatmap(confusion_matrix, annot=True, fmt='d')
plt.pyplot.xlabel('Predicted')
plt.pyplot.ylabel('Truth')