# 00 Fundamental TensorFlow

## Tensorflow
Tensorflow merupakan suatu library yang berguna untuk preprocessing data terutama dalam machine learning. Tensorflow mirip dengan pengolahan numpy.
Berikut adalah keunggulan dari tensorflow:
* Penyediaan banyak library untuk machine learning
* cocok untuk melakukan pemodelan machine learning sehingga melakukan trainging dengan sangat cukup cepat menggunakan TPU (Tensor Processing Unit) yang disediakan oleh google dan dapat menggunakan GPU (Graphic Processing Unit) yang mana hal ini tidak bisa dilakukan di numpy.
* Tensorflow merupakan library yang dikhusus kan untuk AI, sehingga menggunakan tensorflow akan sangat powerfull dalam pemodelan AI.
* AI tidak dapat membaca secara mentah-mentah text atau gambar untuk di training, sehingga diperlu perubahan data menjadi bentuk numerik atau angka. Tensorflow dapat melakukan hal tersebut contohnya menggunakan funngsi [`tf.io`](https://www.tensorflow.org/api_docs/python/tf/io) dan [`tf.data`](https://www.tensorflow.org/guide/data).

In [ ]:
import datetime
datetime.date.today()

datetime.date(2023, 9, 11)

### Let's Start

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.13.0


### [`Tf.Constant()`](https://www.tensorflow.org/api_docs/python/tf/constant)

In [ ]:
# Scalar
tf.constant(3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# Vector
tf.constant([3, 1])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 1], dtype=int32)>

In [ ]:
# Matrix
tf.constant([[3, 2],
            [2, 1]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 2],
       [2, 1]], dtype=int32)>

In [ ]:
# Tensor
tf.constant([[[2, 2],
               [3, 1]],
              [[3, 1],
              [2, 4]]])

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[2, 2],
        [3, 1]],

       [[3, 1],
        [2, 4]]], dtype=int32)>

Terlihat perbedaan scalar, vector, matrix, dan tensor. Untuk Penjelasan [`matematis-nya`](https://www.mathsisfun.com/algebra/scalar-vector-matrix.html). Jumlah dimensi untuk tensor itu n, yang mana artinya tidak terbatas (arbitary). "Tensor merupakan representasi dunia", coba liat di youtube [`penjelasanynya`](https://www.youtube.com/watch?v=f5liqUk0ZTw&pp=ygUOd2hhdCBpcyB0ZW5zb3I%3D)

> `terdapat perbedaan antara int32 dan int64. perbedaannya adalah dari segi bitnya (ex: 32-bit). hal ini menandakan kepresisian dari suatu data, dengan demikan semakin presisi semakin banyak space yang dibutuhkan didalam komputer.`

In [ ]:
from numpy import float32
tensor = tf.constant([[[2, 2],
               [3, 1]],
              [[8, 9],
              [6, 4]]], dtype=float32)
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[2., 2.],
        [3., 1.]],

       [[8., 9.],
        [6., 4.]]], dtype=float32)>

In [ ]:
tensor.ndim # jumlah dimensi tensor

3

![difference between scalar, vector, matrix, tensor](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-scalar-vector-matrix-tensor.png)

### [`Tf.Variable()`](https://www.tensorflow.org/api_docs/python/tf/Variable)

In [ ]:
from numpy import int16

tf.Variable([[[2, 2],
               [1, 1]],
              [[3, 1],
              [2, 4]]], dtype= int16)

<tf.Variable 'Variable:0' shape=(2, 2, 2) dtype=int16, numpy=
array([[[2, 2],
        [1, 1]],

       [[3, 1],
        [2, 4]]], dtype=int16)>

> Perbedaan dari fungsi constant dan variable adalah `variable` dapat dilakukan perubahan didalam isi numeriknya sendangkan `constant` tidak bisa dirubah

Biasanya tensorflow akan memilah sendiri (disaat load data dari model)

### Random Tensor
pada AI terdapat penerapan metode untuk melakukan pembelajaran. hal ini berada pada insialisasi bobot (weight). pada neural network diterapkan gradient discent untuk AI menerapkan mempelajari pola dari data yang diberikan.


**Bagaimana AI belajar**
![how a network learns](https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/images/00-how-a-network-learns.png)


### [`Tf.random.Generator()`](https://www.tensorflow.org/guide/random_numbers#the_tfrandomgenerator_class)

In [ ]:
g1 = tf.random.Generator.from_seed(1)
print(g1.normal(shape=[2, 3]))
g2 = tf.random.get_global_generator()
print(g2.normal(shape=[2, 3]))

tf.Tensor(
[[ 0.43842274 -0.53439844 -0.07710262]
 [ 1.5658046  -0.1012345  -0.2744976 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.27752092  2.3636305   0.93158   ]
 [ 0.10310897 -1.7457939   0.31526667]], shape=(2, 3), dtype=float32)


random tensor diatas terlihat random, akan tetapi sebenarnya tidak random. hal ini karena menggunakan [pseudorandom numbers](https://www.computerhope.com/jargon/p/pseudo-random.htm).

hal ini sama dengan menggunakan `numpy.seed(42)`. Adanya paramter `seed` akan memebuat komputer menghasilkan nilai yang sama walaupun digenerate random.

In [ ]:
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[2., 2.],
        [3., 1.]],

       [[8., 9.],
        [6., 4.]]], dtype=float32)>

In [ ]:
tf.random.shuffle(tensor)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[2., 2.],
        [3., 1.]],

       [[8., 9.],
        [6., 4.]]], dtype=float32)>

In [ ]:
tf.random.shuffle(tensor, seed= 42)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[8., 9.],
        [6., 4.]],

       [[2., 2.],
        [3., 1.]]], dtype=float32)>

Pada shuffle tensor diatas menggunakan seed, jika di run akan menghasilkan nilai tensor yang berbeda (random) yang mana harusnya nilainya sama jika menggunakan seed. hal ini terjadi karna aturan dari tensor [`tf.random.seed`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

In [ ]:
tf.random.set_seed(32)
tf.random.shuffle(tensor, seed = 32)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[8., 9.],
        [6., 4.]],

       [[2., 2.],
        [3., 1.]]], dtype=float32)>

### [`tf.ones()`](https://www.tensorflow.org/api_docs/python/tf/ones)

Agar mudah membuat tensor

In [ ]:
tf.ones(shape = (4, 2, 2))

<tf.Tensor: shape=(4, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

numpy bisa dirubah ke bentuk tensor. hal yang membuat numpy dan tensor sangat berbeda adalah, tensor dapat dijalankan di GPU

> ❗ Untuk pengintepretasian variable nilai vector menggunakan huruf kecil 'x', 'y'. untuk pengintepretasian variable nilai matrix menggunakan huruf besar 'X', 'Y'

In [ ]:
import numpy as np
nump = np.arange(0, 240, dtype=int16)
nump

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
tensor2 = tf.constant(nump, shape = (2, 3, 2, 4, 5))
tensor2

<tf.Tensor: shape=(2, 3, 2, 4, 5), dtype=int16, numpy=
array([[[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]]],


        [[[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]],

         [[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]]],


        [[[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]],



       [[[[120, 121, 122, 123, 124],


### Tensor Vocabulary
* Shape -> Panjang dari element dimensi dari tensor
* Rank -> banyaknya dimensi dari tensor
* Axis atau dimensi -> dimensi dari tensor
* Size -> banyaknya angka didalam tensor

untuk menambahkan dimensi dari tensor terdapat 2 cara: menggunakan tf.newaxis atau [`tf.expand_dims()`](https://www.tensorflow.org/api_docs/python/tf/expand_dims).

In [ ]:
tensor2.shape, tensor2.ndim

(TensorShape([2, 3, 2, 4, 5]), 5)

In [ ]:
tensor2[..., tf.newaxis].shape

TensorShape([2, 3, 2, 4, 5, 1])

In [ ]:
tf.expand_dims(tensor2, axis = -1).shape

TensorShape([2, 3, 2, 4, 5, 1])

### Manipulasi Tensor (+, -, /, *)

> Disarankan menggunakan fungsi dari tensorflow agar kinerja dari tensor lebih baik.

sepertinya ada cara untuk melihat bagaimana kinerja deeplearning pada tensorflow menggunakan [TensorFlow graph](https://www.tensorflow.org/tensorboard/graphs). COBA!!!

In [ ]:
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[2., 2.],
        [3., 1.]],

       [[3., 1.],
        [2., 4.]]], dtype=float32)>

In [ ]:
tensor * 2

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[4., 4.],
        [6., 2.]],

       [[6., 2.],
        [4., 8.]]], dtype=float32)>

In [ ]:
tf.multiply(tensor, 2)

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[4., 4.],
        [6., 2.]],

       [[6., 2.],
        [4., 8.]]], dtype=float32)>

Pada matric terdapat aturan untuk melakukan perkalian dan pembagian sesama matrix ([reff](https://www.mathsisfun.com/algebra/matrix-multiplying.html)). Untuk [tf.matmul()](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul) atau bisa juga menggunaka @.

In [ ]:
X = tf.constant([[2, 3],
                [3, 5]])
X

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 5]], dtype=int32)>

In [ ]:
tf.matmul(X, X)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 21],
       [21, 34]], dtype=int32)>

In [ ]:
X @ X

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 21],
       [21, 34]], dtype=int32)>


sama seperti numpy juga terdapat fungsi untuk reshape dan transpose dari matrix :
* [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape)
* [`tf.transpose()`](https://www.tensorflow.org/api_docs/python/tf/transpose)

In [ ]:
# juga ada shortcut untuk melakukan perkalian dari transpose
tf.matmul(a=X, b=X, transpose_a=True, transpose_b=False)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 21],
       [21, 34]], dtype=int32)>

In [ ]:
tf.matmul(a=X, b=X, transpose_a=True, transpose_b=True)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 21],
       [21, 34]], dtype=int32)>

Pada manipulasi data, sangat penting dikuasai untuk penyesuaian bentuk data untuk modeling.

In [ ]:
# untuk perkalian matrix, juga dapat digunakan menggunakan tf.tensordot()
tf.tensordot(tf.transpose(X), X, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 21],
       [21, 34]], dtype=int32)>

### Merubah tipe data dari tensor

Perubahan tipe data sangat penting. contohnya untuk tipe data int64 akan sangat memekan ruang dari komputasi dari pada int16. meminimum kan ruang komputasi akan sangat berguna agar perangkat dapat berjala dengan ringan seperti di handphone.

Untuk merubah datatype, dapat menggunakan [tf.cast()](https://www.tensorflow.org/api_docs/python/tf/cast)

In [ ]:
X

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [3, 5]], dtype=int32)>

In [ ]:
tf.cast(X, dtype=float32)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [3., 5.]], dtype=float32)>

### Nilai absolute

Sama seperti numpy, untuk dapat menggunakan fungsi absolute menggunakan fungsi tf.abs()

In [ ]:
X = tf.Variable(np.arange(-5, 10), shape=(3,5))

ValueError: ignored

tf.variable() tidak dapat mengimplementasikan fungsi shape

In [ ]:
X = tf.constant(np.arange(-5, 10), shape=(5,3))
X

<tf.Tensor: shape=(5, 3), dtype=int64, numpy=
array([[-5, -4, -3],
       [-2, -1,  0],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])>

In [ ]:
tf.abs(X)

<tf.Tensor: shape=(5, 3), dtype=int64, numpy=
array([[5, 4, 3],
       [2, 1, 0],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

### Finding the min, max, mean, sum (aggregation)

untuk mencari nilai min, max, mean, sum standar devisiasi dan variant, dapat menggunakan syntax `reduce()-[aksi]`. Contoh syntaxnya adalah sbb:

* [`tf.reduce_min()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_min).
* [`tf.reduce_max()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_max).
* [`tf.reduce_mean()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_mean).
* [`tf.reduce_sum()`](https://www.tensorflow.org/api_docs/python/tf/math/reduce_sum).
* `tf.reduce_std()`
* `tf.reduce_variance()`

* **Note:** , sesuatu yang berada pada `math` module, e.g. `tf.math.reduce_min()` tapi bisa juga menggunakan alias `tf.reduce_min()`.

untuk mencari nilai index yang mengandung nilai max atau min dapat menggunakan:

* [`tf.argmax()`](https://www.tensorflow.org/api_docs/python/tf/math/argmax) untuk mencari nilai max dari tensor
* [`tf.argmin()`](https://www.tensorflow.org/api_docs/python/tf/math/argmin) untuk mencari nilai min dari tensor

### Squeezing tensor (menghilangkan semua single dimensi tensor)

* [`tf.squeeze()`](https://www.tensorflow.org/api_docs/python/tf/squeeze) untuk menghilangkan single dimensi tensor

In [ ]:
S = tf.constant(np.random.randint(0, 100, 25), shape=(1, 5, 1, 5))

In [ ]:
S

<tf.Tensor: shape=(1, 5, 1, 5), dtype=int64, numpy=
array([[[[34, 66, 77, 80, 91]],

        [[24, 91, 16, 55, 14]],

        [[55, 40, 78, 40, 75]],

        [[41, 15, 25,  6, 45]],

        [[93, 44, 12, 93, 24]]]])>

In [ ]:
tf.squeeze(S)

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[34, 66, 77, 80, 91],
       [24, 91, 16, 55, 14],
       [55, 40, 78, 40, 75],
       [41, 15, 25,  6, 45],
       [93, 44, 12, 93, 24]])>

### One hot Encoding
Untuk melakukan penyandian, dapat menggunakan one hot encoding, yang mana pada tensor [`tf.one_hot()`](https://www.tensorflow.org/api_docs/python/tf/one_hot).

juga harus menspesify paramter `depth` sebagai level yang mau di one hot encode

In [ ]:
H = tf.constant(np.random.randint(0, 4, 8))
H

<tf.Tensor: shape=(8,), dtype=int64, numpy=array([1, 2, 1, 1, 3, 1, 2, 3])>

In [ ]:
tf.one_hot(H, depth=10)

<tf.Tensor: shape=(8, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

Untuk mengganti data yang aktif dengan sesuatu nilai, dapat dilakukan dengan menambhakan `on_value` dan `off_value`

In [ ]:
tf.one_hot(H, depth = 4, on_value="BENAR!!!", off_value = "Yaahh!!!")

<tf.Tensor: shape=(8, 4), dtype=string, numpy=
array([[b'Yaahh!!!', b'BENAR!!!', b'Yaahh!!!', b'Yaahh!!!'],
       [b'Yaahh!!!', b'Yaahh!!!', b'BENAR!!!', b'Yaahh!!!'],
       [b'Yaahh!!!', b'BENAR!!!', b'Yaahh!!!', b'Yaahh!!!'],
       [b'Yaahh!!!', b'BENAR!!!', b'Yaahh!!!', b'Yaahh!!!'],
       [b'Yaahh!!!', b'Yaahh!!!', b'Yaahh!!!', b'BENAR!!!'],
       [b'Yaahh!!!', b'BENAR!!!', b'Yaahh!!!', b'Yaahh!!!'],
       [b'Yaahh!!!', b'Yaahh!!!', b'BENAR!!!', b'Yaahh!!!'],
       [b'Yaahh!!!', b'Yaahh!!!', b'Yaahh!!!', b'BENAR!!!']], dtype=object)>

### Squaring, log, square root

Untuk operasi matematika:

* [`tf.square()`](https://www.tensorflow.org/api_docs/python/tf/math/square) Untuk melihat mengoprasikan square
* [`tf.sqrt()`](https://www.tensorflow.org/api_docs/python/tf/math/sqrt) Untuk implementasi square root (**note:** element nya harus berupa float, jika tidak akan terjadi error).
* [`tf.math.log()`](https://www.tensorflow.org/api_docs/python/tf/math/log) untuk implementasi log pada setiap value pada tensor (element harus berupa tipe floats).

### Manipulating `tf.variable` tensor

Untuk memanipulasi tensor yang menggunakan variable
* [`.assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign) untuk menetapkan nilai yang berbeda pada tensor
* [`.add_assign()`](https://www.tensorflow.org/api_docs/python/tf/Variable#assign_add) untuk menambahkan dari nilai yang ada dari variable tensor

In [ ]:
I = tf.Variable(np.arange(0, 5))
I

<tf.Variable 'Variable:0' shape=(5,) dtype=int64, numpy=array([0, 1, 2, 3, 4])>

In [ ]:
I.assign([0, 1, 2, 3, 50])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([ 0,  1,  2,  3, 50])>

In [ ]:
I.assign_add([10, 10, 10, 10, 10])

<tf.Variable 'UnreadVariable' shape=(5,) dtype=int64, numpy=array([10, 11, 12, 13, 60])>

### Tensors ke NumPy

tensor dapat di konfersi kedalam bentuk numpy dengan 2 cara.

* `np.array()`
* `tensor.numpy()`


> **Tensor defaultnya menggunakan float32 dari pada float64. Hal ini dikarenakan neural network (yang biasanya menggunakan tensor) umumnya bisa bekerja dengan baik dengen presisi yang kecil yaitu 32-bit**
